### ISSUE TITLE
Set up lint tool

### ISSUE THREAD

**Issue by andreaseliasson** [pintheworld/pintheworld#10]
TSLint seems to be a reasonable option:

---> https://palantir.github.io/tslint/

**Comment by andreaseliasson** [comment]
TSLint seems to be a reasonable options at this stage.
--> https://palantir.github.io/tslint/

**Comment by blanche** [comment]
now that you mention it, we should probably check with the lecturer, that we are allowed to use TS instead of JS before we go ahead^

**Comment by andreaseliasson** [comment]
True.. Since TS is a superset of JS, I think we should be fine, but yes, we should make sure we're allowed.

**Comment by blanche** [comment]
did you hear back from the lecturer yet?

**Comment by andreaseliasson** [comment]
No, I haven't heard anything back from him :/

**Comment by blanche** [comment]
this issue should also include checking style guidelines

**Comment by blanche** [comment]
@andreaseliasson did you have any particular tool in mind to check the style guidlines?
