### ISSUE TITLE
Scoring Function

### ISSUE THREAD

**Issue by JaneJiangHH** [pintheworld/pintheworld#12]

**Comment by blanche** [comment]
are we going to implement the scoring function in the frontend or backend?

**Comment by JaneJiangHH** [comment]
I think both are all right. It won't make much difference

Get Outlook for iOShttps://aka.ms/o0ukef

On Wed, Oct 19, 2016 at 9:58 AM +0100, "blanche" <notifications@github.com<mailto:notifications@github.com>> wrote:

are we going to implement the scoring function in the frontend or backend?

##

**Comment by blanche** [comment]
I think we should implement it in the backend to have a central point for calculating and storing the scores. distributed calculation of the scores is going to be hard later on, when we want to do async stuff

**Comment by blanche** [comment]
closed by #48
