### ISSUE TITLE
deploy webapp to GAE

### ISSUE THREAD

**Issue by blanche** [pintheworld/pintheworld#33]
find a way to deploy webapp(the js part) to GAE automatically from git

**Comment by andreaseliasson** [comment]
To build the frontend, run `npm run build`.
The frontend resources are located in the `js-src/dist` directory.

**Comment by blanche** [comment]
no dist folder :(

**Comment by blanche** [comment]
my mistake! forgot the "run" in "npm run build"

**Comment by blanche** [comment]
are you sure its working though? get an error `enableProdMode is not defined`
EDIT: uncommenting it works fine (from src/main.js:5)

**Comment by blanche** [comment]
can we have something in between build and serve, where the files are deployed to a specific folder, but are updated as you go? otherwise we will have to run the long build for every change and we will need to also host the JS files via the gae-dev server locally for the websocket stuff to work

**Comment by andreaseliasson** [comment]
That would be ideal yes. Should we use a CI tool such as Travis?
https://travis-ci.org
https://docs.travis-ci.com/user/deployment/google-app-engine/

**Comment by blanche** [comment]
just as an info, this generally works, i just don't want to close the issue yet because the urls have to be fixed still to work in dev and prod

i dont think we generally need a CI tool but it might help up grade wise?

**Comment by andreaseliasson** [comment]
Ok, cool! Yeah, let's avoid using a CI tool if we don't really have to.

**Comment by blanche** [comment]
closed by #91
