### ISSUE TITLE
Define scoring methods

### ISSUE THREAD

**Issue by blanche** [pintheworld/pintheworld#6]
1) define simple scoring method using only distance
2) define more complex scoring method using distance + time

**Comment by JaneJiangHH** [comment]
Below is what I think about the algorithm:
//score based on time
//timeScoreBase means the best score we think the player can achieve if he reach the bestPlayTime, the value could be 100?
//for bestPlayTime, if there is only 10 seconds for the player to pin the map, bestPlayTime could be 1 second
//playTime could also be less than bestPlayTime. When this happens, player will get a higher score than timeScoreBase
//A is how much we expect the score to decrease for each additional second spent, the value could be 0.9?
 timeScore=timeScoreBase*pow(A,playTime-bestPlayTime);

//score based on distance
//it's hard to define the shape and coordinates of each city/country, so I think we could find a center point(x,y) according to the largest and smallest x&y of each place
//user click's coordinate(ux,uy)
 distanceScore=distanceScoreBase*pow(B,sqrt((ux-x)^2+(uy-y)^2));

//for the game,there may be 10 rounds every time
roundScore[i]=round(timeScore+distanceScore);

//finalScore
var finalScore=0;
for(i=0;i<10;i++){
finalScore=finalScore+roundScore[i];
}
finalScore=round(finalScore/10);
