### ISSUE TITLE
implement play workflow

### ISSUE THREAD

**Issue by blanche** [pintheworld/pintheworld#61]

**Comment by andreaseliasson** [comment]
From my understanding, this is a general issue which ties together all the existing logic and components to make the game work properly, i.e. you can crate a player, play the game, and view the results.

**Comment by blanche** [comment]
IMHO the basics of this is done, but some details are still open like 
- sync rounds for players (i.e. wait to show next city until all players have made a guess)  and only show highscores until all players have finished playing (this should work automatically when you sync up the rounds acctually actually)
- sync room component to show new players entering the room

shall we close this issues and create two new separate ones for the 1st and the 3rd one?

**Comment by blanche** [comment]
created #89, #90 and #88

**Comment by blanche** [comment]
implemented in #77 see created issues for other issues
