### ISSUE TITLE
Define storage model for GAE

### ISSUE THREAD

**Issue by blanche** [pintheworld/pintheworld#7]

**Comment by blanche** [comment]
@andreaseliasson should i request a merge for this yet? its an implementation of most of the basic API calls (e.g. you can create a game, take a guess, create cities and so on) but without any logic yet.. should we use it as a basis for the front-end implementation already? or should we wait with a merge until the API is implemented completely?

**Comment by andreaseliasson** [comment]
@blanche Yeah, you can create a PR for this and then we can merge it into master. Good thing you specified a root directory for the python code. I forgot to do that explicitly for the frontend code.

**Comment by blanche** [comment]
closed with #13
