### ISSUE TITLE
Write up report

### ISSUE THREAD

**Issue by blanche** [pintheworld/pintheworld#98]
https://docs.google.com/document/d/1G-QJlFMtkDsi3fTiDz-BXHNd84Pszjciw4GBSEisy3E/edit

**Comment by andreaseliasson** [comment]
Message to all: I have added a few lines of text here. Some sections need more text and work to them. Feel free to add/edit/delete what you feel is necessary. Bear in mind that the final report has to be exported to a .pdf file file with a font size of 12 or larger.

**Comment by andreaseliasson** [comment]
As of right now, we are missing parts of the statistics section as well as some info about backend design and implementation + critical evaluation.

**Comment by blanche** [comment]
i have included the backend design/implementation section and critical evaluation. also added some developlment/architecture techniques here and there and had to shorten some paragraphs to make space

**Comment by blanche** [comment]
needs to be reviewed but i would consider this as closed
